### ISSUE TITLE
File `samples/cgi/Rakefile` contains old (removed) API, does not work in 3.0.0

### ISSUE THREAD

**Issue by lslezak** [ruby-gettext/gettext#19]
File `samples/cgi/Rakefile` was not updated to the new API, running `rake` fails with this error:

```
rake aborted!
undefined method `create_mofiles' for GetText:Module
```

According to https://github.com/ruby-gettext/gettext/blob/master/doc/text/news.md#300-2013-08-31 it should be replaced by `GetText::Tools::Task`.

I was looking for some example for this replacement and found this :confused:
